<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Invoice #{{ $invoice->invoice_no }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
        }

        .invoice-box {
            width: 100%;
            border: 1px solid #ddd;
            padding: 20px;
        }

        h2 {
            margin-bottom: 20px;
        }

        p {
            margin: 5px 0;
        }

        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="invoice-box">
        <h2>Invoice #{{ $invoice->invoice_no }}</h2>
        <p><strong>Vendor:</strong> {{ $invoice->vendor_name }}</p>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($invoice->invoice_date)->format('d-M-Y') }}</p>
        <p><strong>Due Date:</strong> {{ \Carbon\Carbon::parse($invoice->due_date)->format('d-M-Y') }}</p>
        <p><strong>Amount:</strong> {{ number_format($invoice->amount, 2) }}</p>
        <p><strong>Status:</strong> {{ ucfirst($invoice->status) }}</p>

        <div class="footer">
            <p>Generated by Finance System - {{ now()->format('d-M-Y H:i') }}</p>
        </div>
    </div>
</body>

</html>
